#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

START=`date +%s`

#TODO: Add check for xterm, transset-df, xcompmgr first
[ -n "$XTERM_VERSION" ] && transset-df -a >/dev/null


PS1='[\u@\h \W]\n\$ '
set bell-style none

VIRTUALENVWRAPPER=/usr/bin/virtualenvwrapper.sh
if [ -a $VIRTUALENVWRAPPER ]
  then
    source /usr/bin/virtualenvwrapper.sh
    export WORKON_HOME=~/.virtualenvs
fi

PEBBLE_SDK_PATH=~/pebble-dev/pebble-sdk
if [ -a $PEBBLE_SDK_PATH ]
  then
    export PATH="$PEBBLE_SDK_PATH/bin:$PATH"
  else
    echo "WARNING: Pebble SDK not found"
fi

#Android tools need to see ANDROID_HOME
export ANDROID_HOME=/opt/android-sdk
if [ -a $ANDROID_HOME ]; then
  export PATH="$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools:$ANDROID_HOME/tools"
else
  echo "WARNING: Android SDK not found"
  unset ANDROID_HOME
fi

if ! [ -z $DISPLAY ]; then
  xrdb -merge ~/.Xresources
fi

if hash go 2>/dev/null; then
  export GOPATH=~/.go
  export PATH="$PATH:$GOPATH/bin"
else
  if [ -d $HOME/.go/src ]; then
    export GOPATH=~/.go
    export PATH="$PATH:$GOPATH/src/go/bin"
  else
    echo "WARNING: Go not installed"
  fi

fi

if hash composer 2>/dev/null; then
  export PATH="$PATH:~/.composer/vendor/bin"
else
  echo "WARNING: Composer not installed"
fi

if hash node 2>/dev/null; then
  export PATH="$HOME/.node_modules/bin:$PATH"
else
  echo "WARNING: node not installed"
  if hash nodejs 2>/dev/null; then
    alias node="nodejs"
    echo "noooode"
  fi
fi

if hash ruby 2>/dev/null; then
  export GEMPATH=$(ruby -e "print Gem.user_dir")
  export PATH="$PATH:$GEMPATH/bin"
else
  echo "WARNING: ruby not installed"
fi

#github: ingydotnet/git-hub
if [ -d $HOME/.git-hub ]; then
  export PATH="$HOME/.git-hub/lib:$PATH"
  alias git=hub
  export MANPATH="$HOME/.git-hub/man:$MANPATH"
else
  echo "WARNING: git-hub not installed"
fi

if hash canto-curses 2>/dev/null; then
  alias canto="canto-curses"
else
  echo "WARNING: canto-curses not installed"
fi

if hash chuck 2>/dev/null; then
  #TODO: Put the else statement's contents into this
  echo "Do your TODO for chuck"
else
  echo "WARNING: chuck is not installed"
fi

#export PATH=/home/chris/aur/torch/install/bin:$PATH  # Added automatically by torch-dist
#export LD_LIBRARY_PATH=/home/chris/aur/torch/install/lib:$LD_LIBRARY_PATH  # Added automatically by torch-dist
#export DYLD_LIBRARY_PATH=/home/chris/aur/torch/install/lib:$DYLD_LIBRARY_PATH  # Added automatically by torch-dist

export PATH="$PATH:$HOME/.local/bin"

alias [p="ls;pwd;jobs"
alias ..="cd .. && pwd"

if hash npm 2>/dev/null; then
  #ne - aka npm-exec - Use to execute node_modules
  # within the current project
  # Usage: ne bower
  alias ne="PATH=$(npm bin):$PATH"
else
  echo "WARNING: npm not installed"
fi

if hash ip 2>/dev/null; then
  alias inet="ip addr | grep inet"
else
  echo "WARNING: ip not present; TODO: add inet alt. solution"
fi

if hash vim 2>/dev/null; then
  alias vi="vim"
else
  echo "WARNING: vim not installed"
fi

##
# Aliases
##
alias edb="vi ~/.bashrc; rlb"
alias rlb="source ~/.bashrc && echo '~/.bashrc reloaded'"

alias ls='ls --color=auto'
alias pj='pwd;jobs'

##
# Functions
##
function hawk {
  echo "`date +%F-%T` $USER: $@" >> ~/talkfile
}
function rock {
  if [ "$#" -eq "0" ]; then
    hawk_list_projects
  elif [ "$#" -eq "1" ]; then
    hawk_list_tasks $1 #Pass the project
  elif [ "$#" -eq "2" ]; then
    hawk_start_task $1 $2
  fi
}
function hawk_list_projects {
  echo "Working on..."
  echo "Projects:"
  echo "1)"
  echo "2)"
  # Log action
  echo "`date +%F-%T` $USER [List Projects]: $@" >> ~/talkfile;
}
function hawk_list_tasks {
  if [ "$#" -ne "1" ]; then
    echo "Please supply a project number"
  else
    echo "Tasks for project $1:"
    echo "1)"
    echo "2)"
  fi
  # Log action
  echo "`date +%F-%T` $USER [List Tasks ($1)]: $@" >> ~/talkfile;
}
function hawk_start_task {
  if [ "$#" -ne "2" ]; then
    echo "Please supply a project and task number"
  else
    echo "Starting project $1 task $2"
  fi
  # Log action
  echo "`date +%F-%T` $USER [Start Task ($1 - $2)]: $@" >> ~/talkfile;
}

function test {
  echo "$@"
  echo "$?"
  echo "$*"
}

# Alias to some custom scripts
if [ -a ~/.virtualenvs/monitor/projects/imageViewer.py ]; then
  alias open_image="python ~/.virtualenvs/monitor/projects/imageViewer.py"
else
  echo "WARNING: open_image not available (python script missing)"
fi

# Some custom bash functions

#TODO: Add a link to source for aur() function
#TODO: Add check for Arch Linux before defining this function
function aur() {
  if [ "$#" -ne 1 ]; then
    echo "Usage: $0 aur-package-name (Downloads aur-package-name.tar.gz)"
    return -1
  fi
  base=https://aur.archlinux.org/packages
  pkg=$1
  echo "Downloading $pkg.tar.gz from aur"
  file=${pkg}.tar.gz
  url=$base/${pkg:0:2}/${pkg}/$file

  curl $url > $file

  unset pkg
  unset base
  unset url
  unset file
}

END=`date +%s`

echo ".bashrc took " $(($END-$START)) " seconds"
