set nu
set expandtab
set tabstop=2
let shiftwidth = &tabstop

"More vim-plug tips on https://github.com/junegunn/vim-plug
call plug#begin('~/.vim/plugged')

" Make sure to use single quotes
Plug 'rosenfeld/conque-term'

" Only load vim-javascript when js or html file is opened
Plug 'pangloss/vim-javascript', { 'for': ['js', 'html'] }


call plug#end()

" prevent auto commenting
"autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
