# vim:fileencoding=utf-8:ft=conf:foldmethod=marker
# include ./theme.conf
startup_session ./startup.kitty

enable_audio_bell no

font_family Monaspace Krypton Var
bold_font auto
italic_font auto
bold_italic_font auto
#bold_font Monaspace Krypton Var Bold
#italic_font Monaspace Krypton Var Italic
#bold_italic_font Monaspace Krypton Var Bold Italic
font_size 14.0
disable_ligatures always

modify_font cell_height +2px
modify_font baseline -1.0

#window_border_width 2
#window_margin_width 4
#window_padding_width 8
# active_border_color #7CEA9C
# inactive_border_color #F7F0F0

# The color for the border of inactive windows in which a bell has occurred.
# `tput bel` for a bell to occur.
# bell_border_color #DB3A34

#background_opacity 0.9
#background_image_layout scaled
#background_tint 0.8

# Prevent myself from accidentally closing the entire kitty window
map cmd+w no-op

# resize windows
map ctrl+alt+up resize_window taller
map ctrl+alt+right resize_window wider
map ctrl+alt+down resize_window shorter 3
map ctrl+alt+left resize_window narrower


# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
