[[ -f ~/.bashrc ]] && . ~/.bashrc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/chris/tmp/google-cloud-sdk/path.bash.inc' ]; then . '/Users/chris/tmp/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/chris/tmp/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/chris/tmp/google-cloud-sdk/completion.bash.inc'; fi
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"

# Created by `pipx` on 2024-07-23 03:59:05
export PATH="$PATH:/Users/chris/.local/bin"
